#!/bin/bash
I=1
cat YOUR-DATA-FILE.csv | while read line; do

	IFS=';' WORD_LIST=($line)
	if [ "$I" -gt "1" ] 
		then
	  	datesensor=$(echo ${WORD_LIST[3]}|sed -e 's/^"//'  -e 's/"$//')
		timestamp=$(date -jf "%Y-%m-%d %H:%M:%S" "${datesensor}" +%s)

		data=$(echo ${WORD_LIST[0]}|sed -e 's/^"//'  -e 's/"$//')

		device=$(echo ${WORD_LIST[0]}|sed -e 's/^"//'  -e 's/"$//')

		signal=$(echo ${WORD_LIST[2]}|sed -e 's/^"//'  -e 's/"$//')

  		requette="http://YOUR-SERVICE?id=YOUR-DEVICE&time=$timestamp&data=$data&station=0000&signal=$signal&duplicate=false&udm=2.2&OTHER-DATA"
  		echo "$requette"

  		curl -i  --request POST $requette | sed -n 1p

	fi
	I=$(($I + 1))
  
    # You can change the sleep time to improve speed and test your system
  	sleep 0.3

done
